namespace SonarCopilotFix.SonarQube;

public sealed record SonarIssue(
    string Key,
    string RuleKey,
    string? Severity,
    string? Status,
    string? Type,
    string? CleanCodeAttributeCategory,
    string Component,
    string FilePath,
    int? Line,
    TextRange? TextRange,
    string Message,
    string? Effort,
    IReadOnlyList<string> Tags,
    string? Author,
    Uri IssueUrl,
    SonarRule? Rule,
    CodeSnippet? CodeSnippet,
    string? Project = null,
    string? Hash = null,
    IReadOnlyList<SonarFlow>? Flows = null,
    string? Resolution = null,
    string? Debt = null,
    DateTimeOffset? CreationDate = null,
    DateTimeOffset? UpdateDate = null,
    DateTimeOffset? CloseDate = null,
    string? Organization = null,
    string? ExternalRuleEngine = null,
    string? CleanCodeAttribute = null,
    IReadOnlyList<SonarImpact>? Impacts = null,
    string? IssueStatus = null,
    string? ProjectName = null,
    IReadOnlyList<string>? InternalTags = null,
    string? LastChangeAnalysisUuid = null,
    string? LastChangeSource = null);
